name: Deploy to FTP

on:
  push:
    branches:
      - master

concurrency:
  group: projects-production-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install project dependencies
        run: npm install

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Build Angular
        run: ng build --configuration production

      - name: Deploy to FTP
        run: |
          lftp -e "set ftp:ssl-allow no; set mirror:use-pget-n 5; mirror --reverse --delete --verbose=3 --no-perms --exclude .well-known/ --exclude web.config ./dist/${{ secrets.FTP_DIR }}/browser /${{ secrets.FTP_DIR }}; bye" ftp://${{ secrets.FTP_HOST }} -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }}
